service: returnProject
frameworkVersion: '3'

provider:
  name: aws
  region: ap-south-1
  stage: beta
  runtime: python3.10
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6

plugins:
  - serverless-python-requirements

package:
  individually: true

custom:
  pythonRequirements:
    useStaticCache: false
    useDownloadCache: false


functions:
  returnFile:
    name: return-file-${sls:stage}-lambda # optional, Deployed Lambda name
    handler: handler.lambda_handler
    module: ../_returnApp
    package:
      patterns:
        - '../_returnApp/**'
    logRetentionInDays: 1
    events:
      - http:
          path: /returnFile
          method: get
