service: returnProject
frameworkVersion: '3'

provider:
  name: aws
  region: ap-south-1
  stage: beta
  runtime: python3.10
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6

package:
  individually: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer:
      fileName: ../_returnApp/application/requirements.txt
      description: Description of what the lambda layer does # optional, Description to publish to AWS
      compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
        - python3.10
      compatibleArchitectures: # optional, a list of architectures this layer is compatible with
        - x86_64

functions:
  returnFile:
    name: return-file-${sls:stage}-lambda # optional, Deployed Lambda name
    package:
      artifact: ../_returnApp/application/serverless.zip
    handler: handler.lambda_handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    logRetentionInDays: 1
    events:
      - http:
          path: /returnFile
          method: get
